### ISSUE TITLE
一张2080ti如何设置

### ISSUE THREAD

**Issue by crossover10** [JDAI-CV/fast-reid#203]
我只有一张2080ti的显卡（11G），想跑veriwild的数据集，我的yaml应该怎么设置才能保持准确度
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 10.76 GiB total capacity; 9.35 GiB already allocated; 245.06 MiB free; 9.67 GiB reserved in total by PyTorch)

IMS_PER_BATCH: 128
input_size:[128 128]
这样可以吗

**Comment by crossover10** [comment]
input 应该改成多少才合适

**Comment by L1aoXingyu** [comment]
input 用 256x256，把 batch size 改小可以试试，2080ti 的显存有多大？

**Comment by crossover10** [comment]
batch size 改到64也不可以，只能把input改成128*128才能跑起来，就是不知道会不会影响模型效果。GPU 0; 10.76 GiB total capacity

**Comment by L1aoXingyu** [comment]
batch size 改成 48 吧，instance 16

**Comment by crossover10** [comment]
RuntimeError: "datasets/datasets/VERI-Wild/images" is not found

**Comment by crossover10** [comment]
好的，还有一个问题，就是VERI-Wild的数据集的测试集和训练集要怎么分？
当我的训练好模型  使用测试--eval-only，会报错：RuntimeError: "datasets/datasets/VERI-Wild/images" is not found

**Comment by L1aoXingyu** [comment]
更新一下代码，在试试

**Comment by crossover10** [comment]
> 更新一下代码，在试试

[08/03 09:29:41 fastreid.evaluation.evaluator]: Start inference on 41861 images
[08/03 09:29:42 fastreid.evaluation.evaluator]: Inference done 11/2617. 0.0287 s / batch. ETA=0:01:20
Traceback (most recent call last):
  File "./tools/train_net.py", line 81, in <module>
    args=(args,),
  File "/root/fast-reid/fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 64, in main
    res = Trainer.test(cfg, model)
  File "/root/fast-reid/fastreid/engine/defaults.py", line 462, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/root/fast-reid/fastreid/evaluation/evaluator.py", line 108, in inference_on_dataset
    for idx, inputs in enumerate(data_loader):
  File "/root/anaconda3/envs/tf14/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/tf14/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/root/anaconda3/envs/tf14/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/root/anaconda3/envs/tf14/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/root/anaconda3/envs/tf14/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/envs/tf14/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/root/anaconda3/envs/tf14/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/root/anaconda3/envs/tf14/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/root/anaconda3/envs/tf14/lib/python3.6/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata
更新代码以后，又出现新的问题

**Comment by crossover10** [comment]
这应该是pytorch的错误，我修改了设置加载数据的 num_workers=0，可以正常运行

**Comment by L1aoXingyu** [comment]
你可以试试 `num_workers=2`，这里一般是和硬件有关系，如果进程大多了，可能有的电脑没有那么高的配置。

**Comment by crossover10** [comment]
[08/03 10:41:05] fastreid.evaluation.evaluator INFO: Total inference time: 0:13:59.672087 (0.193830 s / batch per device)
[08/03 10:41:05] fastreid.evaluation.evaluator INFO: Total inference pure compute time: 0:02:44 (0.038014 s / batch per device)
[08/03 10:44:44] fastreid.engine.defaults INFO: Prepare testing set
[08/03 10:44:47] fastreid.data.datasets.bases INFO: => Loaded LargeVeRiWild in csv format: 
[36m| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| query    | 10000   | 10000      | 126         |
| gallery  | 10000   | 128517     | 161         |[0m
[08/03 10:44:47] fastreid.evaluation.evaluator INFO: Start inference on 138517 images
[08/03 10:44:56] fastreid.evaluation.evaluator INFO: Inference done 11/8658. 0.0325 s / batch. ETA=1:12:32

小数据集跑完缺少输出map等信息，我看了results = evaluator.evaluate()，这个函数是pass。
是什么原因呢

**Comment by crossover10** [comment]
> batch size 改成 48 吧，instance 16，size 还是 256x256

instance是指test的batch size是吧，我理解的意思
