### ISSUE TITLE
When using multi GPU training after first eval step, it would hang out/dead lock.

### ISSUE THREAD

**Issue by knaffe** [JDAI-CV/fast-reid#306]
**Log Info:**
Traceback (most recent call last):
  File "./train_net.py", line 71, in <module>
    args=(args,),
  File "../fastreid/engine/launch.py", line 68, in launch
    daemon=False,
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 78, in join
    timeout=timeout,
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

I use one machine with 2 GPU, --num-gpus 2, --machine-rank 0.
My code could be ran in single gpu mode. But when in multi-gpu mode atfer first eval loop(per n[1,or 10 or any] epoch ), the script would hang/dead lock without any errors raising. When use Ctrl+C, it gives me the infos above.

**Comment by L1aoXingyu** [comment]
Please follow the issue instruction, such as `git diff`.

**Comment by knaffe** [comment]
I change a lot in this repo for my work, but use the original tripletsampler. It might be the dataloder problem.
When this error raises, I use the original triplet sampler to eval this problem. `naive or balanced mode`, the error could be reproduced.
When try to deal with this, I find similar problems and solutions which use setting `cv2.setNumThreads(0)` or `np.random.RandomState(self._seed) or random.seed(self._seed)` instead of  ` np.random.seed(self._seed)`
But they doesn't work.
By the way, it GPU Volatile is not balanced, the one is full(normal level) but another is almost 0(10M).

**Comment by L1aoXingyu** [comment]
I usually train with 4 gpus, and didn't run into this problem.

**Comment by knaffe** [comment]
I have solved this problem. I add the feature of logging the best result and saving the best model depending on the issue #52 .  If putting this op only in the main_process, it will be fine. 
By the way, does this repo have the feature of logging best result and saving best model? It seems that the #52 has removed.

**Comment by L1aoXingyu** [comment]
The priority of saving the best model is not high, because I found that almost all the best model is `model_final.pth`.
