### ISSUE TITLE
运行trt_inference.py失败

### ISSUE THREAD

**Issue by berylyellow** [JDAI-CV/fast-reid#576]
运行：
python trt_inference.py --model-path outputs/trt_model/baseline_R101_ibn_se.engine  --input test_data/*.jpg --batch-size 128 --height 256 --width 256 --output trt_output

错误信息：
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin InstanceNormalization_TRT version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (322) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "trt_inference.py", line 187, in <module>
    trt = TrtEngine(args.model_path, batch_size=args.batch_size)
  File "trt_inference.py", line 80, in __init__
    self._context = self._engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
Exception ignored in: <function TrtEngine.__del__ at 0x7fdaee300290>
Traceback (most recent call last):
  File "trt_inference.py", line 177, in __del__
    del self._input
AttributeError: _input
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
Aborted (core dumped)

环境：
tensorrt 7.2.3.4
cuda：10.2
GPU: T4

前面已经成功转成了onnx，engine也转成功了，做这个trt_inference的时候报错了

**Comment by nanhui69** [comment]
> 运行：
> python trt_inference.py --model-path outputs/trt_model/baseline_R101_ibn_se.engine --input test_data/*.jpg --batch-size 128 --height 256 --width 256 --output trt_output
> 
> ## 错误信息：
> [TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin InstanceNormalization_TRT version 1
> [TensorRT] ERROR: safeDeserializationUtils.cpp (322) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
> [TensorRT] ERROR: INVALID_STATE: std::exception
> [TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
> Traceback (most recent call last):
> File "trt_inference.py", line 187, in
> trt = TrtEngine(args.model_path, batch_size=args.batch_size)
> File "trt_inference.py", line 80, in **init**
> self._context = self._engine.create_execution_context()
> AttributeError: 'NoneType' object has no attribute 'create_execution_context'
> Exception ignored in: <function TrtEngine.**del** at 0x7fdaee300290>
> Traceback (most recent call last):
> File "trt_inference.py", line 177, in **del**
> del self._input
> AttributeError: _input
> ## PyCUDA ERROR: The context stack was not empty upon module cleanup.
> ## A context was still active when the context stack was being
> cleaned up. At this point in our execution, CUDA may already
> have been deinitialized, so there is no way we can finish
> cleanly. The program will be aborted now.
> Use Context.pop() to avoid this problem.
> Aborted (core dumped)
> 
> 环境：
> tensorrt 7.2.3.4
> cuda：10.2
> GPU: T4
> 
> 前面已经成功转成了onnx，engine也转成功了，做这个trt_inference的时候报错了
你的问题解决了么？

**Comment by berylyellow** [comment]
我这边是通过在import tensorrt as trt后加这句话解决的：
trt.init_libnvinfer_plugins(None,'')

**Comment by bankxi** [comment]
> 我这边是通过在import tensorrt as trt后加这句话解决的： trt.init_libnvinfer_plugins(None,'')

请问知道这么做的原因吗
